-- Remove all stale external candidate matches that have score=60 and empty highlights
-- (these were generated by the buggy index lookup fallback)
DELETE FROM external_candidate_matches
WHERE score = 60
  AND highlights = '[]'::jsonb
  AND gaps = '[]'::jsonb
  AND fit_reason = 'Score unavailable';

-- Also clear the one valid match so it gets regenerated without location bias
-- (optional — only run this if you want fresh scores for existing candidates)
-- DELETE FROM external_candidate_matches;
